language: node_js

node_js:
  - 8
  - 6

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libpng16-dev
  
script:
  - npm run test
  - npm run build

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
